import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import localFont from "next/font/local";
import { LenisProvider } from "@/components/providers/lenis-provider";
import "lenis/dist/lenis.css";
import { AmbientBackground } from "@/components/Layout/Gradient/AmbientGradient";

const manrope = Manrope({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800"],
  variable: "--font-manrope",
});

const neueMachina = localFont({
  src: [
    {
      path: "../public/fonts/NeueMachina-Light.otf",
      weight: "300",
      style: "normal",
    },
    {
      path: "../public/fonts/NeueMachina-Regular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/NeueMachina-Ultrabold.otf",
      weight: "800",
      style: "normal",
    },
  ],
  variable: "--font-neue-machina",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      suppressHydrationWarning
      lang="en"
      className={cn(
        "h-full dark lenis lenis-smooth",
        manrope.className,
        neueMachina.variable,
      )}
    >
      <body className="min-h-full flex flex-col">
        {/* <AmbientBackground /> */}
        <LenisProvider>{children}</LenisProvider>
      </body>
    </html>
  );
}
